### ISSUE TITLE
[Feature request] remove dead Links

### ISSUE THREAD

**Issue by cnschu** [shapkinaa/noteson-obsidian-plugin#1]
Links leading to nonexisting pages (like notes that are not published yet should be converted into simple text at the time of publishing.

`[[another not yet published Note]] ` in the Note in obsidian should become `another not yet published note` in the published page.

**Comment by shapkinaa** [comment]
i will make this feature

**Comment by cnschu** [comment]
thanks

**Comment by shapkinaa** [comment]
> Links leading to nonexisting pages (like notes that are not published yet should be converted into simple text at the time of publishing.
> 
> `[[another not yet published Note]] ` in the Note in obsidian should become `another not yet published note` in the published page.

check it
