### ISSUE TITLE
links on notes.ru doesn't work

### ISSUE THREAD

**Issue by cnschu** [shapkinaa/noteson-obsidian-plugin#3]
if i share my obsidian notes witrh the plugin on notes.ru and login on noteson.ru afterwards, in the list of shared notes, none of the notes is correctly linked.

1) create Account on noteson.ru
2) share note via noteson plugin for obsidian
3) login on noteson.ru
4) List of shared notes is displayed
5) the link in the displayed list doesn't contain the ID, only the Link to noteson.ru website root. So none of the Links works.

example:
correct URL: https://notes.noteson.ru/8103f5d0adfd14fdeb283e6a35db142a/default/LordAndreaBelisariusNavigator.html
URL linked in the List: https://noteson.ru/
(see also the attached file)
[NotesOn.zip](https://github.com/shapkinaa/noteson-obsidian-plugin/files/15276380/NotesOn.zip)

**Comment by shapkinaa** [comment]
I fix it
